### ISSUE TITLE
Does not support character other than ascii?

### ISSUE THREAD

**Issue by tcqiuyu** [bw2/ConfigArgParse#162]
This is an interesting library. I was going to use it in my project but found it would raise a "UnicodeDecodeError" since my yaml config file contains Chinese characters. I wondered whether I have done the right way or the library does not support utf-8 file?

**Comment by bw2** [comment]
@tcqiuyu can you post the full python error stack trace?

**Comment by tcqiuyu** [comment]
This is my test script
``` python
import configargparse
# This is a test script
p = configargparse.ArgParser(default_config_files=['conf/test.yaml'])
p.parse_args()
```

This is a test yaml
```yaml
###############################################################################
# Flask服务配置模板
###############################################################################

test: hello_world
```

And this is the error trace message
```
Traceback (most recent call last):
  File "/Users/Qiu/anaconda3/envs/corrector/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-6c490a6c61cd>", line 1, in <module>
    p.parse_args()
  File "/Users/Qiu/anaconda3/envs/corrector/lib/python3.6/site-packages/configargparse.py", line 377, in parse_args
    env_vars = env_vars)
  File "/Users/Qiu/anaconda3/envs/corrector/lib/python3.6/site-packages/configargparse.py", line 486, in parse_known_args
    config_items = self._config_file_parser.parse(stream)
  File "/Users/Qiu/anaconda3/envs/corrector/lib/python3.6/site-packages/configargparse.py", line 146, in parse
    for i, line in enumerate(stream):
  File "/Users/Qiu/anaconda3/envs/corrector/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 87: ordinal not in range(128)
```

**Comment by bw2** [comment]
I'm unable to reproduce this error. 
I copied your example (and added `p.add_argument("--test")` so that it would parse `test: hello_world` from the config file). 
It ran without error on MacOSX in python2.7, python3.6 and ipython3.

**Comment by tcqiuyu** [comment]
That is weird 😵. I tried again just now and it works fine. The issue can be closed. Thanks for your clarifying.

**Comment by curzon01** [comment]
Be sure your editor is setup correct to write utf-8 file conf/test.yaml, not other. May be your previous file was not saved using uft-8
