### ISSUE TITLE
Test failures under Python 3.5

### ISSUE THREAD

**Issue by felixonmars** [bw2/ConfigArgParse#31]
I am getting the following test failures with python 3.5.0. Maybe allow_abbrev needs to be supported?

```
======================================================================
ERROR: test_failures_many_groups_listargs (tests.test_configargparse.TestOptionalsDisallowLongAbbreviation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 208, in wrapper
  File "<string>", line 223, in test_failures
  File "<string>", line 218, in _get_parser
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'

======================================================================
ERROR: test_failures_many_groups_sysargs (tests.test_configargparse.TestOptionalsDisallowLongAbbreviation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 208, in wrapper
  File "<string>", line 223, in test_failures
  File "<string>", line 218, in _get_parser
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'

======================================================================
ERROR: test_failures_no_groups_listargs (tests.test_configargparse.TestOptionalsDisallowLongAbbreviation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 208, in wrapper
  File "<string>", line 223, in test_failures
  File "<string>", line 218, in _get_parser
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'

======================================================================
ERROR: test_failures_no_groups_sysargs (tests.test_configargparse.TestOptionalsDisallowLongAbbreviation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 208, in wrapper
  File "<string>", line 223, in test_failures
  File "<string>", line 218, in _get_parser
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'

======================================================================
ERROR: test_failures_one_group_listargs (tests.test_configargparse.TestOptionalsDisallowLongAbbreviation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 208, in wrapper
  File "<string>", line 223, in test_failures
  File "<string>", line 218, in _get_parser
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'

======================================================================
ERROR: test_failures_one_group_sysargs (tests.test_configargparse.TestOptionalsDisallowLongAbbreviation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 208, in wrapper
  File "<string>", line 223, in test_failures
  File "<string>", line 218, in _get_parser
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'

======================================================================
ERROR: test_successes_many_groups_listargs (tests.test_configargparse.TestOptionalsDisallowLongAbbreviation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 208, in wrapper
  File "<string>", line 230, in test_successes
  File "<string>", line 218, in _get_parser
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'

======================================================================
ERROR: test_successes_many_groups_sysargs (tests.test_configargparse.TestOptionalsDisallowLongAbbreviation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 208, in wrapper
  File "<string>", line 230, in test_successes
  File "<string>", line 218, in _get_parser
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'

======================================================================
ERROR: test_successes_no_groups_listargs (tests.test_configargparse.TestOptionalsDisallowLongAbbreviation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 208, in wrapper
  File "<string>", line 230, in test_successes
  File "<string>", line 218, in _get_parser
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'

======================================================================
ERROR: test_successes_no_groups_sysargs (tests.test_configargparse.TestOptionalsDisallowLongAbbreviation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 208, in wrapper
  File "<string>", line 230, in test_successes
  File "<string>", line 218, in _get_parser
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'

======================================================================
ERROR: test_successes_one_group_listargs (tests.test_configargparse.TestOptionalsDisallowLongAbbreviation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 208, in wrapper
  File "<string>", line 230, in test_successes
  File "<string>", line 218, in _get_parser
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'

======================================================================
ERROR: test_successes_one_group_sysargs (tests.test_configargparse.TestOptionalsDisallowLongAbbreviation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 208, in wrapper
  File "<string>", line 230, in test_successes
  File "<string>", line 218, in _get_parser
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'

----------------------------------------------------------------------
Ran 1578 tests in 1.713s

FAILED (errors=12)
```

**Comment by bw2** [comment]
Fixed by a939a6bcbf11fb11fd272c5c49efb96830dd81fc
